<a href="https://colab.research.google.com/github/LucasGleysson/Senac_ML/blob/master/ML_Aula_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aula 05

#Introdução a DataScience

##Numpy

###Criando uma lista

In [2]:
import numpy as np

In [4]:
minhaLista = [0,1,2,3,4,5,6,7,8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

###Tramsformando em um array numpy

In [5]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

###Diferenta entre array e print(array)

In [6]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


###Uma forma simples de criarmos essa lista

In [8]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

###Transformando agora essa lista em um Array Numpy

In [9]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

###Arange: Fazendo as etapas anteriores numa única sintaxe

In [10]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

###Start, stop, step

In [11]:
array3 = np.arange(0,10,0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

###Arredondando os valores obtidos

In [12]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

###Também podemos "forçar" o tipo dos elementos:

In [13]:
array3 = np.arange(0, 10, 0.5, dtype=int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Predeterminar o tipo dos elementos

In [16]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###Preparando os elementos para trabalhar futuramente com tipos float

In [19]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

###Tipo do objeto

In [20]:
type(array4)

numpy.ndarray

###Tipos dos elementos do array

In [21]:
array4.dtype

dtype('float64')

### Criar array digitando

In [22]:
vetor1 = np.array([0,1,2,3,4])
print(vetor1)

[0 1 2 3 4]


###Seleção especifica

In [24]:
vetor1[3]

3

###Selecionando intervalos

In [25]:
vetor1[0:2]

array([0, 1])

###Array de string

In [26]:
s = np.array(['Python','Profissional','Java',"Água"])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [28]:
s = np.array(['Python',1464321315,'Java',"Água"])
s

array(['Python', '1464321315', 'Java', 'Água'], dtype='<U21')

###Alterando um elemento Array

In [29]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

###Tentando incluir um elemento

In [30]:
vetor1[0] = 'Novo Elemento'
vetor1

ValueError: ignored

In [31]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])